### PR TITLE
Feature/shortski

### PR DESCRIPTION
**Pull request by shortski**
This is the sql way of saying 'I need a coffee'.

### CODE REVIEW

**Comment by SD1333** [comment]
although the requester is extremely unfriendly, I approve this pull request

**Comment by tomasde** [comment]
What is this pull request about?

**Comment by tomasde** [comment]
aah now I understand and approve of this!

**Comment by shortski** [comment]
Somebody is assigned but isn't doing anything.

**Comment by shortski** [comment]
@SD1333 , how are you today?

**Pull request merged**
